#!/bin/bash
read -p "Name of host: " Host
oldIP="$(grep "$Host" ~/.ssh/config -A 1 | grep "192.*" --only-matching)"
[ $oldIP ] || exit 1
echo $oldIP
newIP="$(arp -a | awk '{print $2}' | sed 's/[()]//g')"
echo $newIP
[ $newIP ] || exit 1
sed "s/$oldIP/$newIP/" ~/.ssh/config -i
